# Generated by Django 5.1.2 on 2024-10-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.IntegerField(unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['category_name'], name='inventory_c_categor_8e69bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.IntegerField(unique=True)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('store_location', models.CharField(max_length=100, null=True)),
                ('county_number', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['store_number'], name='inventory_s_store_n_e2cf06_idx'), models.Index(fields=['city'], name='inventory_s_city_73e89e_idx'), models.Index(fields=['zip_code'], name='inventory_s_zip_cod_2bec54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(unique=True)),
                ('item_desc', models.CharField(max_length=255)),
                ('pack', models.IntegerField()),
                ('bottle_volume_ml', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('bottles_sold', models.IntegerField()),
                ('sale_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_sold_liters', models.FloatField()),
                ('volume_sold_gallons', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_number'], name='inventory_i_invoice_2c316e_idx'), models.Index(fields=['date'], name='inventory_i_date_143f50_idx'), models.Index(fields=['store'], name='inventory_i_store_i_3706b2_idx'), models.Index(fields=['item'], name='inventory_i_item_id_e0fbd4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_number'], name='inventory_i_item_nu_d739b7_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_desc'], name='inventory_i_item_de_da8345_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['store'], name='inventory_i_store_i_22c0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['vendor'], name='inventory_i_vendor__c83d21_idx'),
        ),
    ]
