# Generated by Django 5.1.2 on 2024-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('store_number', models.IntegerField()),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('store_location', models.CharField(max_length=100, null=True)),
                ('county_number', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('vendor_number', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('item_number', models.IntegerField()),
                ('item_desc', models.CharField(max_length=255)),
                ('pack', models.IntegerField()),
                ('bottle_volume_ml', models.IntegerField()),
                ('state_bottle_cost', models.FloatField()),
                ('state_bottle_retail', models.FloatField()),
                ('bottles_sold', models.IntegerField()),
                ('sale_dollars', models.FloatField()),
                ('volume_sold_liters', models.FloatField()),
                ('volume_sold_gallons', models.FloatField()),
            ],
        ),
    ]
