# Generated by Django 5.1.2 on 2024-10-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state_bottle_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_bottle_retail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
