# Generated by Django 5.1.2 on 2024-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='inventory_i_invoice_2c316e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store_number'], name='inventory_i_store_n_3f7a86_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='inventory_i_date_143f50_idx'),
        ),
    ]
