# Generated by Django 5.1.2 on 2024-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invoice_inventory_i_invoice_2c316e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['city'], name='inventory_i_city_a8b8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['county_number'], name='inventory_i_county__bfbd64_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['zip_code'], name='inventory_i_zip_cod_99fe83_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store_name'], name='inventory_i_store_n_14323f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['category'], name='inventory_i_categor_8872b2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor_name'], name='inventory_i_vendor__92015d_idx'),
        ),
    ]
